name: "PR Formatting"

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review

defaults:
  run:
    shell: bash

permissions:
  statuses: write
  pull-requests: read

jobs:
  title-check:
    name: Title Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Check PR Title
        uses: step-security/action-semantic-pull-request@75d2dd5deafa3e9fccc1626ecd58d076ed1d2c79 # v6.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
